// Version : 1.0
// Fichier généré par generer-svg-data.html — ne pas modifier à la main.
// Chaque chemin est relatif au dossier svg/.
window.SVG_BANK = {
  "Seconde": {
    "files": [
      "Lycee/seconde_01.svg",
      "Lycee/seconde_02.svg",
      "Lycee/seconde_03.svg",
      "Lycee/seconde_04.svg",
      "Lycee/seconde_05.svg",
      "Lycee/seconde_06.svg",
      "Lycee/seconde_07.svg",
      "Lycee/seconde_08.svg",
      "Lycee/seconde_09.svg",
      "Lycee/seconde_10.svg",
      "Lycee/seconde_11.svg",
      "Lycee/seconde_12.svg",
      "Lycee/seconde_13_diagramme-des-ensembles-de-nombres-n-z-q-r.svg",
      "Lycee/seconde_14_le-vecteur-ab.svg",
      "Lycee/seconde_15_cercle-dans-un-repere-cartesien.svg"
    ]
  },
  "Premiere": {
    "files": [
      "Lycee/premiere_algebre_01_polynome-du-second-degre-parabole-sommet-racines.svg",
      "Lycee/premiere_algebre_02_fonctions-trigonometriques-sin-x-et-cos-x.svg",
      "Lycee/premiere_algebre_03_suite-arithmetique-points-alignes.svg",
      "Lycee/premiere_algebre_04_suite-geometrique-croissance-exponentielle.svg",
      "Lycee/premiere_algebre_05_matrices-22-transformation-du-plan.svg",
      "Lycee/premiere_algebre_06_systeme-lineaire-33-representation-geometrique.svg",
      "Lycee/premiere_algebre_07_equation-aux-valeurs-propres.svg",
      "Lycee/premiere_algebre_08_table-de-cayley-du-groupe-symetrique-s3.svg",
      "Lycee/premiere_analyse_01_fonction-derivee-pente-locale.svg",
      "Lycee/premiere_analyse_02_taux-de-variation-secante.svg",
      "Lycee/premiere_analyse_03_tangente-interpretation-geometrique.svg",
      "Lycee/premiere_analyse_04_fonctions-derivables-usuelles-visualisation.svg",
      "Lycee/premiere_analyse_05_fonction-exponentielle.svg",
      "Lycee/premiere_analyse_06_fonction-logarithme.svg",
      "Lycee/premiere_analyse_07_etude-de-fonctions-tableau-de-variations.svg",
      "Lycee/premiere_analyse_08_fonctions-composees-schema.svg",
      "Lycee/premiere_analyse_09_le-theoreme-des-accroissements-finis.svg",
      "Lycee/premiere_geometrie_01_vecteur-dans-le-plan.svg",
      "Lycee/premiere_geometrie_02_somme-de-vecteurs.svg",
      "Lycee/premiere_geometrie_03_produit-scalaire-et-angle.svg",
      "Lycee/premiere_geometrie_04_droite-dans-le-plan.svg",
      "Lycee/premiere_geometrie_05_vecteurs-colineaires.svg",
      "Lycee/premiere_geometrie_06_triangle-et-hauteur.svg",
      "Lycee/premiere_geometrie_07_distance-d-un-point-a-une-droite.svg",
      "Lycee/premiere_geometrie_08_fonctions-trigonometriques-sur-le-cercle-unite.svg",
      "Lycee/premiere_geometrie_09_theoreme-de-pythagore.svg",
      "Lycee/premiere_probabilites_01_loi-discrete-tableau-de-probabilites.svg",
      "Lycee/premiere_probabilites_02_histogramme-serie-statistique.svg",
      "Lycee/premiere_probabilites_03_nuage-de-points-correlation.svg",
      "Lycee/premiere_probabilites_04_esperance-centre-de-gravite.svg",
      "Lycee/premiere_probabilites_05_arbre-de-probabilites.svg",
      "Lycee/premiere_probabilites_06_intervalle-de-fluctuation-schema.svg",
      "Lycee/premiere_probabilites_07_diagramme-de-probabilite-conditionnelle.svg",
      "Lycee/premiere_probabilites_08_fonction-de-masse-d-une-loi-binomiale.svg",
      "Lycee/premiere_probabilites_09_intersection-de-deux-ensembles-a-et-b.svg"
    ]
  },
  "Terminale": {
    "files": [
      "Lycee/terminale_01_derivee-pente-locale-et-tangente.svg",
      "Lycee/terminale_02_derivee-seconde-convexite-concavite-point-d-inflexion.svg",
      "Lycee/terminale_03_tableau-de-variations-terminale.svg",
      "Lycee/terminale_04_primitive-famille-de-courbes-c-constante.svg",
      "Lycee/terminale_05_integrale-definie-aire-sous-la-courbe.svg",
      "Lycee/terminale_06_integration-par-parties-ipp-schema-visuel.svg",
      "Lycee/terminale_07_comparaison-d-integrales-croissance.svg",
      "Lycee/terminale_08_valeur-moyenne-d-une-fonction-sur-a-b.svg",
      "Lycee/terminale_09_l-integrale-comme-aire-sous-la-courbe.svg",
      "Lycee/terminale_10_representation-d-un-nombre-complexe-diagramme-d-argand.svg",
      "Lycee/terminale_11_formule-d-euler-dans-le-plan-complexe.svg",
      "Lycee/terminale_12_le-groupe-cyclique-des-heures-d-une-horloge.svg",
      "Lycee/terminale_13_principe-du-chiffrement-a-cle-publique.svg",
      "Lycee/terminale_14_le-determinant-comme-volume-d-un-parallelepipede.svg",
      "Lycee/terminale_15_un-graphe-oriente.svg",
      "Lycee/terminale_16_polygone-regulier-annote-hexagone.svg",
      "Lycee/terminale_17_un-arbre-avl-equilibre.svg"
    ]
  },
  "L1": {
    "files": [
      "L1/l1_01.svg",
      "L1/l1_02.svg",
      "L1/l1_03.svg",
      "L1/l1_04.svg",
      "L1/l1_05.svg",
      "L1/l1_06.svg",
      "L1/l1_07.svg",
      "L1/l1_08.svg",
      "L1/l1_09.svg",
      "L1/l1_10.svg",
      "L1/l1_11.svg",
      "L1/l1_12.svg",
      "L1/l1_13.svg",
      "L1/l1_14.svg",
      "L1/l1_15.svg",
      "L1/l1_16.svg",
      "L1/l1_17.svg",
      "L1/l1_18.svg",
      "L1/l1_19.svg",
      "L1/l1_20.svg",
      "L1/l1_21.svg",
      "L1/l1_22.svg",
      "L1/l1_23.svg",
      "L1/l1_24.svg",
      "L1/l1_25.svg",
      "L1/l1_26.svg",
      "L1/l1_27.svg",
      "L1/l1_28.svg",
      "L1/l1_29.svg",
      "L1/l1_30.svg",
      "L1/l1_31.svg",
      "L1/l1_32.svg",
      "L1/l1_33.svg",
      "L1/l1_34.svg",
      "L1/l1_35.svg",
      "L1/l1_36.svg",
      "L1/l1_37.svg",
      "L1/l1_38.svg",
      "L1/l1_39.svg",
      "L1/l1_40.svg",
      "L1/l1_41.svg",
      "L1/l1_42.svg",
      "L1/l1_43.svg",
      "L1/l1_44.svg",
      "L1/l1_45.svg",
      "L1/l1_46.svg",
      "L1/l1_47.svg",
      "L1/l1_48.svg",
      "L1/l1_49.svg",
      "L1/l1_50.svg",
      "L1/l1_51.svg",
      "L1/l1_52.svg",
      "L1/l1_53.svg",
      "L1/l1_54.svg",
      "L1/l1_55.svg",
      "L1/l1_56.svg",
      "L1/l1_57.svg",
      "L1/l1_58.svg",
      "L1/l1_59.svg",
      "L1/l1_60_la-fonction-sinus-et-son-polynome-de-taylor.svg",
      "L1/l1_61_image-d-une-application-lineaire-dans-le-plan.svg"
    ]
  },
  "L2": {
    "files": [
      "L2/l2_01_diagonalisation.svg",
      "L2/l2_02_formes-quadratiques.svg",
      "L2/l2_03_topologie-boule-ouverte.svg",
      "L2/l2_04_series-fourier.svg",
      "L2/l2_05_projection-orthogonale-hilbert.svg",
      "L2/l2_06_theoreme-central-limite.svg",
      "L2/l2_07_pendule-portrait-phase.svg",
      "L2/l2_08_minkowski.svg",
      "L2/l2_09_les-trois-sections-coniques-d-un-double-cone.svg",
      "L2/l2_10_boules-unites-pour-differentes-normes.svg"
    ]
  },
  "L3": {
    "files": [
      "L3/l3_01_topologie-ouvert-voisinage.svg",
      "L3/l3_02_mesure-lebesgue.svg",
      "L3/l3_03_analyse-complexe-residus.svg",
      "L3/l3_04_theorie-galois-tour.svg",
      "L3/l3_05_frenet-courbure.svg",
      "L3/l3_06_plan-tangent-surface.svg",
      "L3/l3_07_martingale-temps-arret.svg",
      "L3/l3_08_machine-turing.svg",
      "L3/l3_09_graphe-de-la-fonction-gamma.svg"
    ]
  },
  "M1": {
    "files": [
      "M1/m1_01_spectre-operateur.svg",
      "M1/m1_02_equation-chaleur.svg",
      "M1/m1_03_geodesique-sphere.svg",
      "M1/m1_04_liouville-flot-hamiltonien.svg",
      "M1/m1_05_mouvement-brownien.svg",
      "M1/m1_06_puits-potentiel-quantique.svg",
      "M1/m1_07_p-vs-np.svg",
      "M1/m1_08_descente-gradient.svg"
    ]
  },
  "M2": {
    "files": [
      "M2/m2_01_calcul-variations.svg",
      "M2/m2_02_fonction-gamma.svg",
      "M2/m2_03_courbe-elliptique.svg",
      "M2/m2_04_poincare-disque.svg",
      "M2/m2_05_transport-optimal.svg",
      "M2/m2_06_lorenz-attracteur.svg",
      "M2/m2_07_feynman-diagramme.svg",
      "M2/m2_08_cosmologie-flrw.svg"
    ]
  }
};
